import { CHALK_VOICE, VIDEO_RULES, VOICE_SUFFIX } from './shared';

export { VOICE_SUFFIX } from './shared';

export const VIDEO_ASSISTANT_SYSTEM_PROMPT = `${CHALK_VOICE}
${VIDEO_RULES}

CONTEXT:
- <watched_content> is primary; <upcoming_content> is secondary. Reference upcoming only with "this comes up later around [timestamp]".
- When <selected_interval> is present, the user selected a specific video range. Focus your answer on that section above all else. Cite timestamps within the interval.
- Cite [M:SS] for claims. "At [3:45], the speaker explains..."
- 2-4 sentences for simple questions. Expand for summaries/notes.

FORMAT:
- **Bold** for key terms. Bullet lists for summaries. Numbered lists for steps.
- No headers, no code blocks unless discussing code.
- $LaTeX$ for math: "x squared" becomes $x^2$.

TOOLS:
- When <knowledge_graph> is provided, you have 8 tools available:
  - cite_moment: Rich clickable timestamps with labels
  - reference_video: Cross-video links with thumbnails
  - search_knowledge: Find concepts/videos across the knowledge base
  - get_prerequisites: Prerequisite chain for any concept (use when user is confused)
  - get_quiz: Pre-computed quiz questions (use when user says "quiz me")
  - get_chapter_context: Chapter info + moments at a timestamp
  - explain_differently: Find alternative explanations from other videos/channels
  - get_learning_path: Shortest path between two concepts in the prerequisite graph
- Without knowledge graph, fall back to [M:SS] text citations.
- Programmatic tools (get_prerequisites, get_quiz, get_chapter_context, explain_differently, get_learning_path) are free — use them liberally.`;

export const EXPLORE_MODE_SYSTEM_PROMPT = `${CHALK_VOICE}
${VIDEO_RULES}

You are guiding the user through the video. YOU ask THEM questions; you do not just answer.

BEHAVIOR:
- 1-2 short sentences max per response. Never paragraphs.
- End EVERY response with 3-4 pill options: <options>opt1|opt2|opt3|opt4</options>
- Options: 2-6 words each, specific to THIS video. Mix: deeper, new topic, test understanding, apply knowledge.
- When the user has covered their goal: "Solid grasp on this. Explore something else or wrap up?"
- Draw connections to related videos when curriculum context is available.`;

const CACHE_OPTS = { anthropic: { cacheControl: { type: 'ephemeral' as const } } };

type SystemPart = { role: 'system'; content: string; providerOptions?: typeof CACHE_OPTS };

/**
 * Builds system prompt as cached parts for Anthropic prompt caching.
 * Part 1 (base + video meta): cached. Part 2 (transcript): cached. Part 3 (position): uncached.
 */
export function buildVideoSystemPromptParts(opts: {
  transcriptContext: string;
  currentTimestamp: string;
  videoTitle?: string;
  summary?: string;
  transcriptSource?: string;
  voiceMode?: boolean;
  intervalDesc?: string;
}): SystemPart[] {
  let basePrompt = VIDEO_ASSISTANT_SYSTEM_PROMPT;

  if (opts.videoTitle) {
    basePrompt += `\n\n<video_title>${opts.videoTitle}</video_title>`;
  }
  if (opts.summary) {
    basePrompt += `\n\n<video_summary>${opts.summary}</video_summary>`;
  }
  if (opts.transcriptSource?.includes('whisper')) {
    basePrompt += `\n\n<transcript_quality>Auto-generated by speech recognition. May contain errors in technical terms and proper nouns.</transcript_quality>`;
  }
  if (opts.voiceMode) {
    basePrompt += VOICE_SUFFIX;
  }

  return [
    { role: 'system', content: basePrompt, providerOptions: CACHE_OPTS },
    {
      role: 'system',
      content: `<transcript_context>\n${opts.transcriptContext}\n</transcript_context>`,
      providerOptions: CACHE_OPTS,
    },
    {
      role: 'system',
      content: `<current_position>The user is at ${opts.currentTimestamp} in the video.${opts.intervalDesc || ''}</current_position>`,
    },
  ];
}

/**
 * Builds explore mode system prompt as cached parts.
 * Part 1 (base + goal): cached. Part 2 (transcript): cached. Part 3 (position): uncached.
 */
export function buildExploreSystemPromptParts(opts: {
  transcriptContext: string;
  currentTimestamp: string;
  videoTitle?: string;
  exploreGoal?: string;
  transcriptSource?: string;
  intervalDesc?: string;
}): SystemPart[] {
  let basePrompt = EXPLORE_MODE_SYSTEM_PROMPT;

  if (opts.videoTitle) {
    basePrompt += `\n\n<video_title>${opts.videoTitle}</video_title>`;
  }
  if (opts.exploreGoal) {
    basePrompt += `\n\n<user_learning_goal>${opts.exploreGoal}</user_learning_goal>`;
  }
  if (opts.transcriptSource?.includes('whisper')) {
    basePrompt += `\n\n<transcript_quality>Auto-generated transcript. May contain errors.</transcript_quality>`;
  }

  return [
    { role: 'system', content: basePrompt, providerOptions: CACHE_OPTS },
    {
      role: 'system',
      content: `<full_transcript>\n${opts.transcriptContext}\n</full_transcript>`,
      providerOptions: CACHE_OPTS,
    },
    {
      role: 'system',
      content: `<current_position>${opts.currentTimestamp}${opts.intervalDesc || ''}</current_position>`,
    },
  ];
}

/**
 * Legacy string builder for explore mode (used by route when not using cached parts).
 */
export function buildExploreSystemPrompt(opts: {
  transcriptContext: string;
  currentTimestamp: string;
  videoTitle?: string;
  exploreGoal?: string;
  transcriptSource?: string;
}): string {
  const parts = buildExploreSystemPromptParts(opts);
  return parts.map(p => p.content).join('\n\n');
}
